name: Release Obsidian plugin

on:
  push:
    tags:
      - "*"

env:
  PLUGIN_NAME: obsidian-ai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ericcornelissen/git-tag-annotation-action@v2
        id: tag-data

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: Build
        id: build
        run: |
          npm install
          npm run build
          mkdir ${{ env.PLUGIN_NAME }}
          cp main.js manifest.json styles.css ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}
          ls
          echo "tag_name=$(git tag --sort version:refname | tail -n 1)" >> $GITHUB_ENV

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ env.tag_name }}
          body: ${{ steps.tag-data.outputs.annotation }}
          token: ${{ secrets.GH_TOKEN }}
          artifacts: ${{ env.PLUGIN_NAME }}.zip,manifest.json,main.js,styles.css
          allowUpdates: true
          removeArtifacts: true
